#!/bin/sh
set -e

if [ -- != -$TRACE- ]; then
        set -x
fi

: ${BREWFILE:="/usr/local/share/agshoes/Brewfile"}
brew update
brew upgrade
brew bundle --file="${BREWFILE}"

SRCDIR="$HOME/Dropbox/src"
: ${CFGDIR:="${SRCDIR}/github.com/josephholsten/jh-ansible"}
cd "${CFGDIR}"
sudo echo > /dev/null
exec bin/run "$@"
